package sdl3go

/*
#include <SDL3/SDL.h>
*/
import "C"

type Window struct {
	handle *C.SDL_Window
}

type WindowFlags uint32

const (
	WINDOW_FULLSCREEN         WindowFlags = C.SDL_WINDOW_FULLSCREEN
	WINDOW_OPENGL             WindowFlags = C.SDL_WINDOW_OPENGL
	WINDOW_OCCLUDED           WindowFlags = C.SDL_WINDOW_OCCLUDED
	WINDOW_HIDDEN             WindowFlags = C.SDL_WINDOW_HIDDEN
	WINDOW_BORDERLESS         WindowFlags = C.SDL_WINDOW_BORDERLESS
	WINDOW_RESIZABLE          WindowFlags = C.SDL_WINDOW_RESIZABLE
	WINDOW_MINIMIZED          WindowFlags = C.SDL_WINDOW_MINIMIZED
	WINDOW_MAXIMIZED          WindowFlags = C.SDL_WINDOW_MAXIMIZED
	WINDOW_MOUSE_GRABBED      WindowFlags = C.SDL_WINDOW_MOUSE_GRABBED
	WINDOW_INPUT_FOCUS        WindowFlags = C.SDL_WINDOW_INPUT_FOCUS
	WINDOW_MOUSE_FOCUS        WindowFlags = C.SDL_WINDOW_MOUSE_FOCUS
	WINDOW_EXTERNAL           WindowFlags = C.SDL_WINDOW_EXTERNAL
	WINDOW_HIGH_PIXEL_DENSITY WindowFlags = C.SDL_WINDOW_HIGH_PIXEL_DENSITY
	WINDOW_MOUSE_CAPTURE      WindowFlags = C.SDL_WINDOW_MOUSE_CAPTURE
	WINDOW_ALWAYS_ON_TOP      WindowFlags = C.SDL_WINDOW_ALWAYS_ON_TOP
	WINDOW_UTILITY            WindowFlags = C.SDL_WINDOW_UTILITY
	WINDOW_TOOLTIP            WindowFlags = C.SDL_WINDOW_TOOLTIP
	WINDOW_POPUP_MENU         WindowFlags = C.SDL_WINDOW_POPUP_MENU
	WINDOW_KEYBOARD_GRABBED   WindowFlags = C.SDL_WINDOW_KEYBOARD_GRABBED
	WINDOW_VULKAN             WindowFlags = C.SDL_WINDOW_VULKAN
	WINDOW_METAL              WindowFlags = C.SDL_WINDOW_METAL
	WINDOW_TRANSPARENT        WindowFlags = C.SDL_WINDOW_TRANSPARENT
	WINDOW_NOT_FOCUSABLE      WindowFlags = C.SDL_WINDOW_NOT_FOCUSABLE
)
